# Generated by Django 6.0.6 on 2026-06-24 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("trips", "0004_alter_tripapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="trip",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="trips.trip",
            ),
            preserve_default=False,
        ),
    ]
