# Generated by Django 6.0.6 on 2026-06-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_alter_trip_return_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripapplication",
            name="application_message",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
