# Generated by Django 6.0.6 on 2026-06-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_trip_return_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="total_seats",
            field=models.PositiveIntegerField(default=4),
        ),
    ]
