# Generated by Django 6.0.6 on 2026-06-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_tripapplication_application_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("kicked", "Kicked"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
