# Generated by Django 6.0.6 on 2026-07-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_alter_tripapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripapplication",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tripapplication",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
