# Generated by Django 6.0.6 on 2026-07-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_tripapplication_is_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripapplication",
            name="payment_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
