# Generated by Django 6.0.6 on 2026-07-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0006_tripapplication_payment_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("kicked", "Kicked"),
                    ("waiting_payment", "Waiting for payment"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
