# Generated by Django 6.0.6 on 2026-07-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0007_alter_tripapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
