# Generated by Django 6.0.6 on 2026-08-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0008_trip_is_available"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="total_cost",
            new_name="cost_per_person",
        ),
    ]
